# see recommended basic mockery config:
# https://vektra.github.io/mockery/latest/configuration/#recommended-basic-config
with-expecter: True
all: True
#dir: mocks
#dir: "{{.PackagePath}}"
#keeptree: True
inpackage: True
packages:
  github.com/gigurra/flycd/internal/fly_client:
    config:
      dir: "internal/fly_client"
  github.com/gigurra/flycd/internal/flycd:
    config:
      dir: "internal/flycd"
