# see recommended basic mockery config:
# https://vektra.github.io/mockery/latest/configuration/#recommended-basic-config
with-expecter: True
all: True
#dir: mocks
#dir: "{{.PackagePath}}"
#keeptree: True
#filename: "{{.InterfaceName}}_mocks_test.go"
packages:
  github.com/gigurra/flycd/pkg/fly_client:
    config:
      dir: "mocks/pkg/fly_client"
  github.com/gigurra/flycd/pkg/flycd:
    config:
      dir: "mocks/pkg/flycd"
