name: "app1"
description: "test app 1 for testing. lalala"

fly.toml:
  prepend: # merging not yet implemented
  append: # merging not yet implemented
  overwrite:
    app: project1-app1
    primary_region: "arn" # default region for tests is Stockholm/Sweden
    services:
      - internal_port: 80
        force_https: true
        auto_stop_machines: true
        auto_start_machines: true
        min_machines_running: 1
        concurrency:
          type: "requests"
          soft_limit: 200
          hard_limit: 250
        ports:
          - handlers: ["http"]
            port: 80
            force_https: true
          - handlers: ["tls", "http"]
            port: 443


source:
  repo: "github.com/username/repo"
  path: "path/to/app"
  ref: "refs/heads/master"
  #ref: "refs/tags/v1.0.0"
