
app: &app project1-app1-foobar12341
description: "test app 1 for testing. lalala"

primary_region: "arn" # default region for tests is Stockholm/Sweden
services:
  - internal_port: 80
    protocol: "tcp"
    force_https: true
    auto_stop_machines: true
    auto_start_machines: true
    min_machines_running: 1
    concurrency:
      type: "requests"
      soft_limit: 200
      hard_limit: 250
    ports:
      - handlers: ["http"]
        port: 80
        force_https: true
      - handlers: ["tls", "http"]
        port: 443

# Point to a repo. You are expected to mount the necessary ssh keys to the container
source:
  repo: "git@github.com:username/repo"
  path: "path/to/app"
  ref: "refs/heads/master"

# Modify to your needs. By default, we will create a new fly.io
# app without any user interaction/confirmation.
# For the most simple apps, you probably don't need to modify these at all
launch_params:
  - "--ha=false"
  - "--auto-confirm"
  - "--now"
  - "--copy-config"
  - "--name"
  - *app

# Modify to your needs. By default, we will deploy the fly.io
# app without any user interaction/confirmation.
# For the most simple apps, you probably don't need to modify these at all
deploy_params: []


