############################
## Basic configuration
app: &app example-project1-local-app-foobar12341
org: &org personal

# Point where the code is.
source:
  type: "local"
  #path: somewhere/else/

############################
## Optional configuration
env:
  ENV: "development"

primary_region: &primary_region "arn" # default region for tests
services:
  - internal_port: 80
    protocol: "tcp"
    force_https: true
    auto_stop_machines: true
    auto_start_machines: true
    min_machines_running: 0
    concurrency:
      type: "requests"
      soft_limit: 200
      hard_limit: 250
    ports:
      - handlers: ["http"]
        port: 80
        force_https: true
      - handlers: ["tls", "http"]
        port: 443

# Modify to your needs. By default, we will create a new fly.io
# app without any user interaction/confirmation.
# For the most simple apps, you probably don't need to modify these at all
launch_params:
  - "--ha=false"
  - "--auto-confirm"
  - "--now"
  - "--copy-config"
  - "--name"
  - *app
  - "--region"
  - *primary_region
  - "--org"
  - *org

# Modify to your needs. By default, we will deploy the fly.io
# app without any user interaction/confirmation.
# For the most simple apps, you probably don't need to modify these at all
deploy_params:
  - "--ha=false"


